/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

/**
 *
 * @author Logan
 */
public class NotificationPanel extends javax.swing.JPanel {

    public MiniGamePanel miniGamePanel;

    /**
     * Creates new form NotificationPanel
     */
    public NotificationPanel(MiniGamePanel miniGamePanel) {
        initComponents();
        this.miniGamePanel = miniGamePanel;
        this.jLabelQuizLevel.setText("Quiz Level: " + miniGamePanel.currentQuestion.getDifficulty());
        this.jLabelScoreEarn.setText("Score Earn: " + miniGamePanel.score);
        int correctAnswerIndex = this.miniGamePanel.currentQuestion.getCorrectOptionIndex() - 1;
        this.jLabelAnswer.setText("Correct Answer: " + miniGamePanel.currentQuestion.getQuestionOptions()[correctAnswerIndex]);
        miniGamePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelScoreEarn = new javax.swing.JLabel();
        jLabelAnswer = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelQuizLevel = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelScoreEarn.setText("Score Earn: ");

        jLabelAnswer.setText("Correct Answer:");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelQuizLevel.setText("Quiz Level: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAnswer)
                            .addComponent(jLabelQuizLevel)
                            .addComponent(jLabelScoreEarn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuizLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelScoreEarn)
                .addGap(12, 12, 12)
                .addComponent(jLabelAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.miniGamePanel.resultFrame.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelAnswer;
    private javax.swing.JLabel jLabelQuizLevel;
    private javax.swing.JLabel jLabelScoreEarn;
    // End of variables declaration//GEN-END:variables
}
